# Markov Chains

*Leandro Mineti*

*Last edit: December 2018*

### TLDR

When someone brings a Markov chain to the table, you should remember three important concepts:

- Markov property.
- Transition matrix.
- Stationary distribution.

## Introduction

A Markov chain is an important example of a stochastic process. "A sequence of random variables $X_1, X_2, ...$ is called a *stochastic process* or *random process* with *discrete time parameter*. The first random variable $X_1$ is called the *initial state* of the process; and for $n = 2,3,...$, the random variabel $X_n$ is called the *state of the proecss at time n*."[1]. It is important to note the difference of these sequences of random variables and the ones appreciated in other parts of statistics, like the proof of the Law of Large Numbers. In a Stochastic Process the random variables are not necessarily independent and identically distributed (iid). In fact, an interesting point in stochastic processes is assessing the dependence of these random variables over time. Generally, we want to define probability distribution of the next state $X_{n+1}$, given the states that already happened:

$$Pr(X_{n+1} = j \mid X_n = i, X_{n-1} = i_{n-1}, X_{n-2} = i_{n-2}, ...)$$

### Markov property

The Markov chain models a memoryless stochastic process. The probability of the next state depends only on the present one, this is known as the **Markov property**. This simplifies the above equation to:

$$Pr(X_{n+1} = j \mid X_n = i)$$

That is to say that the past and future are conditionally independent given the present [2]. Considering a finite Markov chain with k possible states where $k = 1, 2, ...$, "the conditional distributions of the state at time $n+1$ given the state at time $n$, that is, $Pr(X_{n+1} = j \mid X_n = i)$ for $i, j = 1, ..., k$ and $n = 1,2,...$, are called *transition distributions* of the Markov chain"[1]. If this distribution does not change over time, the Markov chain is called homogeneous or has stationary transition distribution. 

## Transition matrix

"Consider a finite Markov chain with stationary transition distributions given by $p_{ij} = Pr(X_{n+1} = j \mid X_n = i)$ for all $n,i,j$. The *transition matrix* of the Markov chain is defined to be the $k \times k$ matrix $\mathbf{P}$ with elements $p_{ij}$."[1]

$$\mathbf{P} = 
 \begin{pmatrix}
  p_{11} & p_{12} & \cdots & p_{1k} \\
  p_{21} & p_{22} & \cdots & p_{2k} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  p_{k1} & p_{k2} & \cdots & p_{kk} 
 \end{pmatrix}$$


Let's use a transition matrix to define a Markov chain with 5 states.

In [0]:
import numpy as np

# Define transition matrix
transition_matrix = np.array([[0.4, 0.6, 0, 0, 0],
                             [0, 0, 0.9, 0, 0.1],
                             [0.4, 0, 0.1, 0.5, 0],
                             [0.2, 0.7, 0, 0, 0.1],
                             [0.5, 0, 0, 0.5, 0]])

We can visualize the Markov chain defined by the above transition matrix as a graph.
![alt text](https://storage.googleapis.com/leandro-random/markov-chain-graph.png)

As every line on the matrix represents a probability to move from a given state to another, all the numbers in each line must sum to one. Besides, all elements need to be nonnegative. A square matrix with these properties is known as a [stochastic matrix](https://en.wikipedia.org/wiki/Stochastic_matrix).

In [0]:
# Sum of each line
np.sum(transition_matrix, axis = 1)

array([1., 1., 1., 1., 1.])

## Initial distribution

We can define the initial probability of each state as a row vector $\mathbf{v}$ of size $k$ where k is the number of states in the Markov chain and each element $v_i$ for $i = 1, 2, ..., k$ is the probability of the state $k$. This is vector is called the *initial distribution* of the chain.

$$\mathbf{v} = [ v_i, v_2, ..., v_k ]$$ 

With the probability vector and transition matrix we can define the probability of each state after one step as:

$$\mathbf{v_{n+1}} = \mathbf{v_{n}P}$$ 

We can generalize this formulation for $s$ steps:

$$\mathbf{v_{n+s}} = \mathbf{v_{n}P}^s$$ 

Let's begin with a initial distribution where we know we are at state 1 and calculate the probabilites after one step.

In [0]:
state = np.array([1, 0, 0, 0, 0])

state @ transition_matrix

array([0.4, 0.6, 0. , 0. , 0. ])

As defined by our graph, when on state A we have a probability of 0.6 of moving to state B and 0.4 of staying at A. The distribution vector makes sense. Suppose now, we want to calculate the distribution after 10 steps. Using the last equation:

In [0]:
state @ np.linalg.matrix_power(transition_matrix, 10)

array([0.27745538, 0.28189331, 0.23522178, 0.16504972, 0.04037981])

We got the probabilities of being in each state after 10 steps when the initial distribution was $\mathbf{v} = [1, 0, 0, 0, 0]$. What if we try another initial distribution?

In [0]:
state_2 = np.array([0.7, 0, 0.1, 0, 0.2])

state_2 @ np.linalg.matrix_power(transition_matrix, 10)

array([0.27496154, 0.26573116, 0.24972629, 0.16938226, 0.04019874])

The results are very similar! This brings us to our last concept, the **stationary distribution**.

### Stationary distribution

Under some general conditions that I will not go into, "a probability vector $\mathbf{v}$ that satisfies $\mathbf{vP} = \mathbf{v}$ is called a *stationary distribution* for the Markov chain" [1]. That formulation reminds us of our linear algebra classes, a vector with that property is called the **eigenvector** of a matrix. That is to say that we have a closed form for the stationary distribution of a Markov chain, which is awesome. For our chain we have:

In [0]:
# Choose the left eigenvector
v = np.linalg.eig(transition_matrix.T)[1][:,0]

# Normalization 'l1' to make sure the elements sum up to one
v.real / np.linalg.norm(v.real, ord = 1)

array([0.26588235, 0.26823529, 0.26823529, 0.15529412, 0.04235294])

We can start with any initial distribution and the distribution will converge to the abover vector when the number of steps $s \rightarrow \infty$. Cool!

## Conclusion

Now we have some basic tools for future explorations on Markov chains. If you want to keep studying, there is an important tool that is built upon Markov chains: Markov Chain Monte Carlo. It is seen everywhere on Bayiesian inference and has many real world applications. The details of MCMC can be a little daunting, if you want a cool application of Markov chains to try out your skills, here is a nice one: [Chutes and Ladders](https://jakevdp.github.io/blog/2017/12/18/simulating-chutes-and-ladders/) [4]. 

## References

[1] DeGroot, M. H., & Schervish, M. J. (2012). Probability and statistics. Pearson Education.

[2] Harvard University. (n.d.). Lecture 31: Markov Chains | Statistics 110. Retrieved from https://www.youtube.com/watch?v=8AJPs3gvNlY

[3] Harvard University. (n.d.). Lecture 32: Markov Chains Continued | Statistics 110. Retrieved from https://www.youtube.com/watch?v=aBGOyZv2pZE

[4] Simulating Chutes & Ladders in Python | Pythonic Perambulations. (n.d.). Retrieved January 10, 2019, from https://jakevdp.github.io/blog/2017/12/18/simulating-chutes-and-ladders/
